---

# This playbook used to populate /root/.docker/config.json and  /var/lib/origin/.docker/config.json .
# That responsibility is now moved to a systemd unit enabled in the AMIs (ops-registry-secret-sync.service).
# This prevents the scenario where the daemon config image can't be pulled from the ops registry because
# of out-of-date credentials.

# Note: The next 3 tasks are trying to work around https://bugzilla.redhat.com/show_bug.cgi?id=1592503
#  When this bug is closed, these should be removed
- name: DNS lookup the docker registry ip
  shell: "getent hosts docker-registry.default.svc.cluster.local | awk '{print $1}'"
  changed_when: false
  register: registry_ip_cmd

- name: debug docker registry ip
  debug:
    msg: "{{ registry_ip_cmd }}"

- name: create symlink for docker registry ip
  file:
    path: "/host/etc/docker/certs.d/{{ registry_ip_cmd.stdout }}:5000"
    src: "docker-registry.default.svc:5000"
    state: link
    force: True
  when: registry_ip_cmd.stdout != ''
#### END of https://bugzilla.redhat.com/show_bug.cgi?id=1592503
