---
galaxy_info:
  author: OpenShift Operations
  description: A role to manage OpenShift group policy
  company: Red Hat
  license: Apache
  min_ansible_version: 1.9
  platforms:
  - name: EL
    versions:
    - 7
  categories:
  - cloud
dependencies:
  - "aos_{{ osgp_openshift_version }}_roles/lib_openshift"
